add Intents-States-UIModel
islamversity/Reyan pull request #10
Opened 2020-08-10 18:36 UTC by meghdadfm

Add Search UIModel - Intents - RowActionModel - Result and States

2020-08-11 07:21 UTC, helloseyedjafari reviewed
Thanks for the definitions.
please remove all the files in `.idea` directory

2020-08-11 07:21 UTC, worldsnas commented on search/src/commonMain/kotlin/com/islamversity/search/SearchIntent.kt
> +//    data class NextPage(
if we don't need it please delete it.
if we need it please uncomment it!

2020-08-11 07:21 UTC, worldsnas commented on search/src/androidMain/kotlin/com/islamversity/search/view/SearchView.kt
> +//            }
if we don't need it please delete it 
if we need it please uncomment it

2020-08-11 07:21 UTC, worldsnas commented on search/src/commonMain/kotlin/com/islamversity/search/SearchResult.kt
> +    data class Data(val items : List<SoraUIModel>) : SearchResult()
`Data` is a very vague name.
What do you think about "Found"

2020-08-11 07:21 UTC, worldsnas commented on search/src/commonMain/kotlin/com/islamversity/search/SearchState.kt
> +    val items : List<SoraUIModel>? = null
I guess we can remove the nullibility and use `emptyList` instead

2020-08-11 20:09 UTC, rezaiyan commented on domain/src/commonMain/kotlin/com/islamversity/domain/model/sora/SoraUIModel.kt
> +
Extra space!

2020-08-11 20:09 UTC, rezaiyan commented on search/src/commonMain/kotlin/com/islamversity/search/SearchPresenter.kt
> +            SearchResult.Loading -> TODO()
It's better not to push `TODO `s

2020-08-15 20:32 UTC, IamHaddad approved these changes

2020-08-15 20:56 UTC, rezaiyan requested changes
It seems [Sora](https://github.com/islamversity/Reyan/blob/develop/db/src/commonMain/kotlin/com/islamversity/db/model/Sora.kt) and `SoraEntityModel `are the same.

2020-08-15 21:08 UTC, rezaiyan commented on domain/src/commonMain/kotlin/com/islamversity/domain/repo/SoraSearchRepo.kt
> +package com.islamversity.domain.repo
Is it ok that a specific repository class like `SoraSearchRepo ` has been residing in the domain module, isn't better to be in its own module?

2020-08-15 21:11 UTC, rezaiyan requested changes
Here we have two steps of mapping `Mapper<SoraEntityModel, SoraRepoModel>` and `Mapper<SoraRepoModel, SoraUIModel>`.
Is it really needed?

2020-08-21 09:49 UTC, meghdadfm commented on domain/src/commonMain/kotlin/com/islamversity/domain/repo/SoraSearchRepo.kt
> +package com.islamversity.domain.repo
No, because you may use repositories (Repo class) in other feature modules.

2020-09-02 11:11 UTC, rezaiyan commented
If a new branch has been replaced, this can be closed!

2020-09-04 06:56 UTC, closed without merging